name: Deploy uxopian-ai documentation

on:
  push:
    branches:
      - main  

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Mise en place de Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Installation des dépendances
        run: pip install mkdocs-material

      - name: Déploiement
        run: mkdocs gh-deploy --force
